arch:
  - amd64
  - ppc64le
language: node_js
node_js:
  - "0.10"
notifications:
  email:
    - dustin@dustindiaz.com
before_script:
  - ./node_modules/serve/bin/serve . &

script: phantomjs ./phantom.js
